# -*- coding: utf-8 -*-
"""GWC DATA.AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mubi_96jPpWBemFeBTcR_XAs3Q5-H3YX
"""

from google.colab import files
uploaded=files.upload()
print(uploaded)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

df=pd.read_excel("/content/adult..xlsx")

df.head()

df.tail()

df = df.replace('?', pd.NA)
df = df.dropna()

label_encoders = {}
X = df.drop('income', axis=1)
for column in X.select_dtypes(include='object').columns:
    le = LabelEncoder()
    X[column] = le.fit_transform(X[column])
    label_encoders[column] = le

target_encoder = LabelEncoder()
y = target_encoder.fit_transform(df['income'])

income_counts = df['income'].value_counts()

# Plotting
plt.figure(figsize=(6, 6))
plt.pie(income_counts, labels=income_counts.index, autopct='%1.1f%%', startangle=90, colors=["lightblue", "salmon"])
plt.title("Income Distribution")
plt.axis('equal')  # Equal aspect ratio makes the pie a circle
plt.show()

# Only include numerical columns
corr = X.corr()

# Set plot size
plt.figure(figsize=(10, 8))

# Draw heatmap
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.tight_layout()
plt.show()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", report)

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Initialize and train the SVM model
svm_model = SVC(kernel='rbf')  # You can try 'linear', 'poly', or 'rbf'
svm_model.fit(X_train, y_train)

# Predict using the SVM model
y_pred_svm = svm_model.predict(X_test)

# Evaluate the SVM model
print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print("Classification Report:\n", classification_report(y_test, y_pred_svm))





